### ISSUE TITLE
UnboundLocalError: local variable 'relation' referenced before assignment

### ISSUE THREAD

**Issue by wuhao5688** [vacancy/SceneGraphParser#5]
The sentence triggered this error : "some small birds perch on a square bird-feeder outside."

```
some small birds perch on a square bird-feeder outside.
Traceback (most recent call last):
  File "demo_stdin.py", line 4, in <module>
    graph = sng_parser.parse(sentence)
  File "/home/mdm/code/SceneGraphParser/sng_parser/parser.py", line 122, in parse
    return get_default_parser().parse(sentence, **kwargs)
  File "/home/mdm/code/SceneGraphParser/sng_parser/parser.py", line 70, in parse
    return self.unwrapped.parse(sentence, **kwargs)
  File "/home/mdm/code/SceneGraphParser/sng_parser/backends/spacy_parser.py", line 217, in parse
    if relation is not None:
UnboundLocalError: local variable 'relation' referenced before assignment

```

**Comment by vacancy** [comment]
Bug fixed by 19b25de.
This is a serious bug due to f122ca4, which may affect the parsing result (even if there is no exception). Please upgrade the code and parse all sentences again... Sorry for the inconvenience.
